---
title : "Generative Modeling Workshop"
author: Susan Holmes

---



# Index


```{r setupInitial, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "figures/",  # All figures will go to a 'figures' directory
  cache = TRUE,
  cache.path = "_cache/"
  # other options...
)
```

# Workshop on using generative models

 **Lisbon, 7, 8 May, 2025**


## Our learning goals:

 - Learn how to use simulation tools to solve and understand statistical models.
 - Go over examples of experimental design using generative models.  
 - Use different R packages to simulate data according to a hierarchical model with
 multiple levels of random variation.

## Prerequisites:

- Some statistical know-how and R and RStudio installed on your laptops.
- Some useful buzzwords and acronyms to look up in case: 

 GOF: *Goodness of Fit*
 
 MCMC: *Markov chain Monte Carlo*
 
 ABC: *Approximate Bayesian Computation*
 
 Random generation: From uniform and non-uniform distributions.
 
 Mixtures: Finite combinations of known distributions
 
 Hierarchical Models: Infinite mixtures
 
 GANs: [Generative Adversarial network](https://en.wikipedia.org/wiki/Generative_adversarial_network)
 
 Identifiability
 
 GMM: Gaussian Mixture Models (beware GMM : Generalized Method of Moments)
 
 GLM : Generalized Linear Models
 
 GLMM: General Linear Mixture Models
 
 HMC: Hamiltonian Monte Carlo
 
 
 


